"""empty message

Revision ID: 96695b01a551
Revises: e31040eb3bd1
Create Date: 2022-12-19 19:48:34.688412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96695b01a551'
down_revision = 'e31040eb3bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_message_read_time')

    # ### end Alembic commands ###
